name: Deploy Frontend and Backend to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-project-backend-507414
  REGION: asia-south1
  CLUSTER_NAME: sdd-cluster

  REPOSITORY: sdd-repo

  BACKEND_IMAGE: sdd-backend
  FRONTEND_IMAGE: sdd-frontend

  BACKEND_DEPLOYMENT: sdd-backend
  FRONTEND_DEPLOYMENT: sdd-frontend

  BACKEND_CONTAINER: backend
  FRONTEND_CONTAINER: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/808426301962/locations/global/workloadIdentityPools/sdd-pool/providers/sdd-provider
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build backend Docker image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$GITHUB_SHA \
            ./backend

      - name: Push backend Docker image
        run: |
          docker push \
            asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$GITHUB_SHA

      - name: Build frontend Docker image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$GITHUB_SHA \
            ./frontend

      - name: Push frontend Docker image
        run: |
          docker push \
            asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$GITHUB_SHA

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy backend to GKE
        run: |
          kubectl set image deployment/$BACKEND_DEPLOYMENT \
            $BACKEND_CONTAINER=asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$GITHUB_SHA

      - name: Wait for backend rollout
        run: |
          kubectl rollout status deployment/$BACKEND_DEPLOYMENT --timeout=5m

      - name: Deploy frontend to GKE
        run: |
          kubectl set image deployment/$FRONTEND_DEPLOYMENT \
            $FRONTEND_CONTAINER=asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$GITHUB_SHA

      - name: Wait for frontend rollout
        run: |
          kubectl rollout status deployment/$FRONTEND_DEPLOYMENT --timeout=5m

      - name: Check Pods status
        run: |
          kubectl get pods